name: Build Angular & .NET App

on:
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment for Angular Client
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust if required by your Angular app

      # Step 3: Install Angular dependencies
      - name: Install Angular Dependencies
        run: npm install
        working-directory: ./TblogieeClient

      # Step 4: Build Angular Client
      - name: Build Angular Client
        run: npm run build
        working-directory: ./TblogieeClient

      # Step 5: Set up .NET SDK for the Server
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Step 6: Restore .NET dependencies
      - name: Restore .NET Dependencies
        run: dotnet restore
        working-directory: ./TblogieeServer

      # Step 7: Build .NET Server
      - name: Build .NET Server
        run: dotnet build --configuration Release
        working-directory: ./TblogieeServer
